import { Fragment } from 'react';
import type { RunView } from '../../shared/view';
import { latestDiff } from '../lib/console';
import type { FileDiff } from '../lib/diff';
import { clock, plural } from '../lib/format';
import { DemoTag } from './Banners';

const VALIDATION_KEYS = new Set([
  'unitTests',
  'integrationTests',
  'lint',
  'typecheck',
  'healthProbe',
]);
const SIGN = { add: '+', remove: '−', context: ' ' } as const;
const SPOKEN = { add: 'added', remove: 'removed', context: '' } as const;

function FileDiffView({ file }: { file: FileDiff }) {
  return (
    <figure className="diff">
      <figcaption className="diff__file">
        <code>{file.path}</code>
        <span className="diff__stat">
          <span className="diff__add">+{file.additions}</span>
          <span className="diff__del">−{file.deletions}</span>
        </span>
      </figcaption>
      <div className="diff__scroll">
        <table className="diff__table">
          <tbody>
            {file.hunks.map((hunk) => (
              <Fragment key={hunk.header}>
                <tr className="diff__hunk">
                  <td colSpan={3}>{hunk.header}</td>
                </tr>
                {hunk.lines.map((line, index) => (
                  <tr
                    key={`${hunk.header}:${String(index)}`}
                    className={`diff__line diff__line--${line.kind}`}
                  >
                    <td className="diff__num">{line.oldLine ?? ''}</td>
                    <td className="diff__num">{line.newLine ?? ''}</td>
                    <td className="diff__code">
                      <span className="diff__sign" aria-hidden="true">
                        {SIGN[line.kind]}
                      </span>
                      {SPOKEN[line.kind] && (
                        <span className="visually-hidden">{SPOKEN[line.kind]}: </span>
                      )}
                      {line.text}
                    </td>
                  </tr>
                ))}
              </Fragment>
            ))}
          </tbody>
        </table>
      </div>
    </figure>
  );
}

/**
 * The candidate fix: why, whether it was validated, and the diff exactly as a sandbox
 * command printed it. It is marked "not applied externally" until an approved action runs.
 */
export function Remediation({ view }: { view: RunView }) {
  const remediation = view.evidence?.remediation ?? null;
  const diff = latestDiff(view);
  const demo = view.source.kind === 'fixture';
  const gated = view.gatedAction?.call ?? null;
  const applied = gated?.approval?.decision === 'allow' && gated.status === 'succeeded';
  const checks = view.gate.required.filter((item) => VALIDATION_KEYS.has(item.key));
  const passed = checks.filter((item) => item.status === 'satisfied').length;

  return (
    <section className="panel" aria-labelledby="remediation-title">
      <div className="panel__head">
        <h2 id="remediation-title" className="label">
          Candidate remediation
        </h2>
        {(remediation || diff) && <span className="chip">Generated by the agent</span>}
        {(remediation || diff) && (
          <span className={`chip ${applied ? 'chip--good' : ''}`}>
            {applied ? `Applied via ${gated.ref.tool} after approval` : 'Not applied externally'}
          </span>
        )}
      </div>
      <div className="panel__body">
        {!remediation && !diff ? (
          <p className="empty">No candidate remediation yet.</p>
        ) : (
          <>
            {remediation && (
              <p className="remediation__reason">
                <span className="sublabel">Reason</span>
                {remediation.summary}{' '}
                <span className="hint">({plural(remediation.attempts, 'attempt')})</span>
              </p>
            )}
            {checks.length > 0 && (
              <p
                className={`remediation__validation ${passed === checks.length ? 'remediation__validation--ok' : ''}`}
              >
                Validation: {passed} of {plural(checks.length, 'required check')} verified in the
                sandbox
              </p>
            )}
            {diff ? (
              <>
                {diff.files.map((file) => (
                  <FileDiffView key={file.path} file={file} />
                ))}
                <p className="hint remediation__source">
                  Printed by <code>{diff.call.exec?.command}</code> at{' '}
                  {clock(diff.call.completedAt)}
                  {diff.call.exec?.truncated ? ', end of the output only' : ''}
                  {demo && <DemoTag />}
                </p>
              </>
            ) : (
              <p className="empty">
                No diff in TrueForge’s record. The fix was applied inside the sandbox; a runbook
                step that prints <code>git diff</code> makes it reviewable here.
              </p>
            )}
          </>
        )}
      </div>
    </section>
  );
}
